--
-- PostgreSQL database dump
--

\restrict tpkw4uHrx2pQljpUmdISURIPFfTibcra3F8ZPN7K6D42OghxmpgqaBwdMuP7kNx

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_profile; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.accounts_profile (
    id bigint NOT NULL,
    image character varying(100),
    full_name character varying(255) NOT NULL,
    bio character varying(255) NOT NULL,
    about text NOT NULL,
    country character varying(100) NOT NULL,
    instagram character varying(200) NOT NULL,
    telegram character varying(200) NOT NULL,
    twitter character varying(200) NOT NULL,
    linkedin character varying(200) NOT NULL,
    website character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.accounts_profile OWNER TO bloguser;

--
-- Name: accounts_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.accounts_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    full_name character varying(255) NOT NULL,
    role character varying(20) NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO bloguser;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO bloguser;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO bloguser;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO bloguser;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO bloguser;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO bloguser;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO bloguser;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO bloguser;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO bloguser;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO bloguser;

--
-- Name: media_mediafile; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.media_mediafile (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    file character varying(100) NOT NULL,
    alt_text character varying(255) NOT NULL,
    file_type character varying(20) NOT NULL,
    file_size bigint,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    uploaded_by_id bigint,
    mime_type character varying(100) NOT NULL,
    CONSTRAINT media_mediafile_file_size_check CHECK ((file_size >= 0))
);


ALTER TABLE public.media_mediafile OWNER TO bloguser;

--
-- Name: media_mediafile_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.media_mediafile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_mediafile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_podcast; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.media_podcast (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(280) NOT NULL,
    summary text NOT NULL,
    content text NOT NULL,
    duration integer,
    status character varying(20) NOT NULL,
    is_featured boolean NOT NULL,
    listens_count integer NOT NULL,
    published_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    audio_file_id bigint,
    author_id bigint,
    category_id bigint NOT NULL,
    cover_image_id bigint,
    CONSTRAINT media_podcast_duration_check CHECK ((duration >= 0)),
    CONSTRAINT media_podcast_listens_count_check CHECK ((listens_count >= 0))
);


ALTER TABLE public.media_podcast OWNER TO bloguser;

--
-- Name: media_podcast_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.media_podcast ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_podcast_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_podcast_tags; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.media_podcast_tags (
    id bigint NOT NULL,
    podcast_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.media_podcast_tags OWNER TO bloguser;

--
-- Name: media_podcast_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.media_podcast_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_podcast_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_video; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.media_video (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(280) NOT NULL,
    summary text NOT NULL,
    content text NOT NULL,
    embed_url character varying(200) NOT NULL,
    duration integer,
    status character varying(20) NOT NULL,
    is_featured boolean NOT NULL,
    views_count integer NOT NULL,
    published_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    author_id bigint,
    category_id bigint NOT NULL,
    thumbnail_id bigint,
    video_file_id bigint,
    CONSTRAINT media_video_duration_check CHECK ((duration >= 0)),
    CONSTRAINT media_video_views_count_check CHECK ((views_count >= 0))
);


ALTER TABLE public.media_video OWNER TO bloguser;

--
-- Name: media_video_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.media_video ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_video_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_video_tags; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.media_video_tags (
    id bigint NOT NULL,
    video_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.media_video_tags OWNER TO bloguser;

--
-- Name: media_video_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.media_video_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_video_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_bookmark; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.news_bookmark (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    post_id bigint NOT NULL
);


ALTER TABLE public.news_bookmark OWNER TO bloguser;

--
-- Name: news_bookmark_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.news_bookmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_category; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.news_category (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title character varying(200) NOT NULL,
    slug character varying(220) NOT NULL
);


ALTER TABLE public.news_category OWNER TO bloguser;

--
-- Name: news_category_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.news_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_comment; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.news_comment (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    text text NOT NULL,
    is_approved boolean NOT NULL,
    user_id bigint NOT NULL,
    post_id bigint NOT NULL
);


ALTER TABLE public.news_comment OWNER TO bloguser;

--
-- Name: news_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.news_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_post; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.news_post (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(280) NOT NULL,
    excerpt character varying(300) NOT NULL,
    content text NOT NULL,
    cover character varying(100),
    status character varying(20) NOT NULL,
    published_at timestamp with time zone,
    views integer NOT NULL,
    author_id bigint NOT NULL,
    category_id bigint,
    homepage_order integer NOT NULL,
    homepage_section character varying(40) NOT NULL,
    is_featured boolean NOT NULL,
    is_hero boolean NOT NULL,
    post_type character varying(30) NOT NULL,
    show_on_homepage boolean NOT NULL,
    CONSTRAINT news_post_homepage_order_check CHECK ((homepage_order >= 0)),
    CONSTRAINT news_post_views_check CHECK ((views >= 0))
);


ALTER TABLE public.news_post OWNER TO bloguser;

--
-- Name: news_post_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.news_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_post_tags; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.news_post_tags (
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.news_post_tags OWNER TO bloguser;

--
-- Name: news_post_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.news_post_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_post_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_tag; Type: TABLE; Schema: public; Owner: bloguser
--

CREATE TABLE public.news_tag (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title character varying(100) NOT NULL,
    slug character varying(120) NOT NULL
);


ALTER TABLE public.news_tag OWNER TO bloguser;

--
-- Name: news_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: bloguser
--

ALTER TABLE public.news_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_profile; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.accounts_profile (id, image, full_name, bio, about, country, instagram, telegram, twitter, linkedin, website, created_at, user_id) FROM stdin;
1		a									2026-06-01 14:53:40.158056+00	1
3		Kermani									2026-06-01 19:36:43.271344+00	3
2	profiles/images_XHCySVn_1.webp	Abbas kermani	asa	asas							2026-06-01 15:54:40.955735+00	2
\.


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, email, full_name, role) FROM stdin;
1	pbkdf2_sha256$1000000$lyEQfgmEdbGEVDHyvPOTSH$XGZKg1JB39qF8uW4dyXM502tKPJbw7bSD0y0ds0M+eo=	\N	f	a			f	t	2026-06-01 14:53:39.966879+00	a@gmail.com	a	user
2	pbkdf2_sha256$1000000$4X8b2k1Oa4YvC33SuzmB2v$j9WRWntBC4RFGJaWSe2YIup6m++5feVidlcyOCADJow=	\N	t	admin			t	t	2026-06-01 15:54:38.629472+00	admin@gmail.com		admin
3	pbkdf2_sha256$1000000$xBFKXrGlnJtldG0kFUkV9N$4j7ht2RaFHFbV7VH3Ecn5LBzYOfc7KMndwv+CM/RlTA=	\N	f	Abbas			f	t	2026-06-01 19:36:43.06677+00	abbaskermani@gmail.com	Kermani	user
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add profile	7	add_profile
26	Can change profile	7	change_profile
27	Can delete profile	7	delete_profile
28	Can view profile	7	view_profile
29	Can add category	8	add_category
30	Can change category	8	change_category
31	Can delete category	8	delete_category
32	Can view category	8	view_category
33	Can add tag	9	add_tag
34	Can change tag	9	change_tag
35	Can delete tag	9	delete_tag
36	Can view tag	9	view_tag
37	Can add post	10	add_post
38	Can change post	10	change_post
39	Can delete post	10	delete_post
40	Can view post	10	view_post
41	Can add comment	11	add_comment
42	Can change comment	11	change_comment
43	Can delete comment	11	delete_comment
44	Can view comment	11	view_comment
45	Can add bookmark	12	add_bookmark
46	Can change bookmark	12	change_bookmark
47	Can delete bookmark	12	delete_bookmark
48	Can view bookmark	12	view_bookmark
49	Can add media file	13	add_mediafile
50	Can change media file	13	change_mediafile
51	Can delete media file	13	delete_mediafile
52	Can view media file	13	view_mediafile
53	Can add podcast	14	add_podcast
54	Can change podcast	14	change_podcast
55	Can delete podcast	14	delete_podcast
56	Can view podcast	14	view_podcast
57	Can add video	15	add_video
58	Can change video	15	change_video
59	Can delete video	15	delete_video
60	Can view video	15	view_video
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	accounts	profile
8	news	category
9	news	tag
10	news	post
11	news	comment
12	news	bookmark
13	media	mediafile
14	media	podcast
15	media	video
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-06-01 13:18:28.875515+00
2	contenttypes	0002_remove_content_type_name	2026-06-01 13:18:28.882703+00
3	auth	0001_initial	2026-06-01 13:18:28.920211+00
4	auth	0002_alter_permission_name_max_length	2026-06-01 13:18:28.925354+00
5	auth	0003_alter_user_email_max_length	2026-06-01 13:18:28.929914+00
6	auth	0004_alter_user_username_opts	2026-06-01 13:18:28.938795+00
7	auth	0005_alter_user_last_login_null	2026-06-01 13:18:28.945221+00
8	auth	0006_require_contenttypes_0002	2026-06-01 13:18:28.947717+00
9	auth	0007_alter_validators_add_error_messages	2026-06-01 13:18:28.958474+00
10	auth	0008_alter_user_username_max_length	2026-06-01 13:18:28.963055+00
11	auth	0009_alter_user_last_name_max_length	2026-06-01 13:18:28.967727+00
12	auth	0010_alter_group_name_max_length	2026-06-01 13:18:28.976788+00
13	auth	0011_update_proxy_permissions	2026-06-01 13:18:28.982604+00
14	auth	0012_alter_user_first_name_max_length	2026-06-01 13:18:28.990724+00
15	accounts	0001_initial	2026-06-01 13:18:29.042768+00
16	admin	0001_initial	2026-06-01 13:18:29.059869+00
17	admin	0002_logentry_remove_auto_add	2026-06-01 13:18:29.065345+00
18	admin	0003_logentry_add_action_flag_choices	2026-06-01 13:18:29.071032+00
19	news	0001_initial	2026-06-01 13:18:29.158295+00
20	media	0001_initial	2026-06-01 13:18:29.17112+00
21	media	0002_mediafile_mime_type_alter_mediafile_file_type_and_more	2026-06-01 13:18:29.249482+00
22	sessions	0001_initial	2026-06-01 13:18:29.258886+00
23	accounts	0002_remove_user_otp_remove_user_reset_token_and_more	2026-06-01 16:08:18.080324+00
24	news	0002_alter_post_options_post_homepage_order_and_more	2026-06-01 23:32:24.666389+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: media_mediafile; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.media_mediafile (id, title, file, alt_text, file_type, file_size, created_at, updated_at, uploaded_by_id, mime_type) FROM stdin;
\.


--
-- Data for Name: media_podcast; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.media_podcast (id, title, slug, summary, content, duration, status, is_featured, listens_count, published_at, created_at, updated_at, audio_file_id, author_id, category_id, cover_image_id) FROM stdin;
\.


--
-- Data for Name: media_podcast_tags; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.media_podcast_tags (id, podcast_id, tag_id) FROM stdin;
\.


--
-- Data for Name: media_video; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.media_video (id, title, slug, summary, content, embed_url, duration, status, is_featured, views_count, published_at, created_at, updated_at, author_id, category_id, thumbnail_id, video_file_id) FROM stdin;
\.


--
-- Data for Name: media_video_tags; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.media_video_tags (id, video_id, tag_id) FROM stdin;
\.


--
-- Data for Name: news_bookmark; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.news_bookmark (id, created_at, updated_at, user_id, post_id) FROM stdin;
\.


--
-- Data for Name: news_category; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.news_category (id, created_at, updated_at, title, slug) FROM stdin;
4	2026-06-03 07:50:50.682898+00	2026-06-03 07:50:50.682912+00	اقتصاد کلان	macroeconomics
5	2026-06-03 07:51:21.818176+00	2026-06-03 07:51:21.818186+00	بازار سرمایه	capital-market
\.


--
-- Data for Name: news_comment; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.news_comment (id, created_at, updated_at, text, is_approved, user_id, post_id) FROM stdin;
\.


--
-- Data for Name: news_post; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.news_post (id, created_at, updated_at, title, slug, excerpt, content, cover, status, published_at, views, author_id, category_id, homepage_order, homepage_section, is_featured, is_hero, post_type, show_on_homepage) FROM stdin;
22	2026-06-03 07:55:08.866655+00	2026-06-03 07:55:16.061347+00	تورم چیست و چرا ایجاد می‌شود	what-is-inflation-and-causes	بررسی مفهوم تورم و دلایل افزایش قیمت‌ها در اقتصاد.	تورم به معنای افزایش مداوم سطح عمومی قیمت‌ها در اقتصاد است. زمانی که تورم بالا می‌رود، قدرت خرید مردم کاهش پیدا می‌کند.	posts/covers/Inflation--scaled.jpg	published	\N	1	2	4	0	none	f	f	news	f
23	2026-06-03 07:58:22.283325+00	2026-06-03 07:58:22.283339+00	رکود اقتصادی چگونه شکل می‌گیرد	how-economic-recession-happens	آشنایی با مفهوم رکود و تاثیر آن بر بازارها.	رکود اقتصادی زمانی رخ می‌دهد که رشد اقتصادی کاهش یافته و تولید و مصرف در اقتصاد افت می‌کند.\r\nدر دوره رکود معمولاً نرخ بیکاری افزایش یافته و سرمایه‌گذاری کاهش پیدا می‌کند.	posts/covers/Economic-indicators-for-recession.webp	published	\N	0	2	4	0	none	f	f	news	f
26	2026-06-03 08:07:35.990364+00	2026-06-03 08:07:47.578116+00	نرخ بهره چه تاثیری بر اقتصاد دارد	interest-rate-impact-on-economy	بررسی نقش نرخ بهره در رشد اقتصادی و تورم.	نرخ بهره یکی از ابزارهای مهم برای کنترل تورم است.\r\n\r\nافزایش نرخ بهره می‌تواند باعث کاهش مصرف و سرمایه‌گذاری شود و در نتیجه تورم را کنترل کند.	posts/covers/hq720.jpg	published	\N	1	2	4	0	none	f	f	news	f
24	2026-06-03 08:01:43.599292+00	2026-06-03 08:02:43.80583+00	سیاست پولی چیست	monetary-policy-basics	نقش بانک مرکزی در کنترل تورم و اقتصاد.	سیاست پولی مجموعه اقداماتی است که بانک مرکزی برای کنترل تورم و مدیریت نقدینگی انجام می‌دهد.\r\n\r\nافزایش یا کاهش نرخ بهره یکی از ابزارهای مهم سیاست پولی است.	posts/covers/images_4d3vz5c.jpg	published	\N	1	2	4	0	none	f	f	news	f
25	2026-06-03 08:03:50.732799+00	2026-06-03 08:04:43.337817+00	تولید ناخالص داخلی چیست	what-is-gdp	معرفی مفهوم GDP و اهمیت آن در اقتصاد.	تولید ناخالص داخلی یا GDP ارزش کل کالاها و خدمات تولید شده در یک کشور طی یک دوره زمانی مشخص است.\r\n\r\nاین شاخص یکی از مهم‌ترین معیارها برای سنجش سلامت اقتصادی کشورها محسوب می‌شود.	posts/covers/6904376624054800f576e27e_GDP_adalah.jpg	published	\N	1	2	4	0	none	f	f	news	f
27	2026-06-03 08:31:10.934934+00	2026-06-03 08:32:32.327739+00	بازار سرمایه چیست	what-is-capital-market	معرفی بازار سرمایه و نقش آن در اقتصاد.	بازار سرمایه محلی برای تامین مالی شرکت‌ها و سرمایه‌گذاری افراد است.\r\n\r\nدر این بازار ابزارهایی مانند سهام و اوراق بهادار معامله می‌شوند.	posts/covers/original-size.webp	published	\N	1	2	5	0	none	f	f	news	f
28	2026-06-03 08:36:51.977912+00	2026-06-03 08:36:51.977922+00	مدیریت ریسک در سرمایه‌گذاری	risk-management-in-investing	اهمیت مدیریت ریسک در بازارهای مالی.	سرمایه‌گذاری بدون مدیریت ریسک می‌تواند زیان‌های سنگینی ایجاد کند.\r\n\r\nتنوع‌بخشی به سبد سرمایه‌گذاری یکی از روش‌های کاهش ریسک است.	posts/covers/Types-of-real-estate-risk-social.webp	published	\N	0	2	5	0	none	f	f	news	f
29	2026-06-03 08:39:13.756513+00	2026-06-03 08:39:13.756526+00	روانشناسی بازار	market-psychology	تاثیر احساسات معامله‌گران بر بازار.	ترس و طمع از مهم‌ترین عوامل تاثیرگذار بر رفتار معامله‌گران هستند.\r\n\r\nدرک روانشناسی بازار می‌تواند به تصمیم‌گیری بهتر کمک کند.	posts/covers/What-is-market-psychology.jpg	published	\N	0	2	5	0	none	f	f	news	f
\.


--
-- Data for Name: news_post_tags; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.news_post_tags (id, post_id, tag_id) FROM stdin;
19	22	5
20	23	6
21	23	7
22	24	8
23	24	9
24	25	6
25	25	7
26	26	8
27	26	9
28	26	10
29	27	8
30	27	13
31	28	10
32	28	13
33	28	14
34	29	10
35	29	13
\.


--
-- Data for Name: news_tag; Type: TABLE DATA; Schema: public; Owner: bloguser
--

COPY public.news_tag (id, created_at, updated_at, title, slug) FROM stdin;
5	2026-06-03 07:51:56.155144+00	2026-06-03 07:51:56.155154+00	macroeconomics	macroeconomics
6	2026-06-03 07:56:03.73174+00	2026-06-03 07:56:03.731751+00	macro	macro
7	2026-06-03 07:56:16.362756+00	2026-06-03 07:56:16.362766+00	economy	economy
8	2026-06-03 08:02:07.584778+00	2026-06-03 08:02:07.584789+00	centra bank	central-bank
9	2026-06-03 08:02:31.379074+00	2026-06-03 08:02:31.379087+00	monetary policy	monetary-policy
10	2026-06-03 08:06:06.223287+00	2026-06-03 08:06:06.223299+00	finance	finance
11	2026-06-03 08:06:21.675245+00	2026-06-03 08:06:21.675256+00	interest-rate	interest-rate
12	2026-06-03 08:30:54.568095+00	2026-06-03 08:30:54.568106+00	investment	investment
13	2026-06-03 08:31:07.229407+00	2026-06-03 08:31:07.229417+00	stock	stock
14	2026-06-03 08:34:01.455443+00	2026-06-03 08:34:01.455459+00	risk-management	risk-management
15	2026-06-03 08:36:17.136482+00	2026-06-03 08:36:17.136494+00	stock-market	stock-market
\.


--
-- Name: accounts_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.accounts_profile_id_seq', 3, true);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 3, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 24, true);


--
-- Name: media_mediafile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.media_mediafile_id_seq', 1, false);


--
-- Name: media_podcast_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.media_podcast_id_seq', 1, false);


--
-- Name: media_podcast_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.media_podcast_tags_id_seq', 1, false);


--
-- Name: media_video_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.media_video_id_seq', 1, false);


--
-- Name: media_video_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.media_video_tags_id_seq', 1, false);


--
-- Name: news_bookmark_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.news_bookmark_id_seq', 1, false);


--
-- Name: news_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.news_category_id_seq', 5, true);


--
-- Name: news_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.news_comment_id_seq', 1, false);


--
-- Name: news_post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.news_post_id_seq', 30, true);


--
-- Name: news_post_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.news_post_tags_id_seq', 36, true);


--
-- Name: news_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bloguser
--

SELECT pg_catalog.setval('public.news_tag_id_seq', 15, true);


--
-- Name: accounts_profile accounts_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile accounts_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_key UNIQUE (user_id);


--
-- Name: accounts_user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: media_mediafile media_mediafile_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_mediafile
    ADD CONSTRAINT media_mediafile_pkey PRIMARY KEY (id);


--
-- Name: media_podcast media_podcast_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_podcast
    ADD CONSTRAINT media_podcast_pkey PRIMARY KEY (id);


--
-- Name: media_podcast media_podcast_slug_key; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_podcast
    ADD CONSTRAINT media_podcast_slug_key UNIQUE (slug);


--
-- Name: media_podcast_tags media_podcast_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_podcast_tags
    ADD CONSTRAINT media_podcast_tags_pkey PRIMARY KEY (id);


--
-- Name: media_podcast_tags media_podcast_tags_podcast_id_tag_id_af122266_uniq; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_podcast_tags
    ADD CONSTRAINT media_podcast_tags_podcast_id_tag_id_af122266_uniq UNIQUE (podcast_id, tag_id);


--
-- Name: media_video media_video_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_video
    ADD CONSTRAINT media_video_pkey PRIMARY KEY (id);


--
-- Name: media_video media_video_slug_key; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_video
    ADD CONSTRAINT media_video_slug_key UNIQUE (slug);


--
-- Name: media_video_tags media_video_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_video_tags
    ADD CONSTRAINT media_video_tags_pkey PRIMARY KEY (id);


--
-- Name: media_video_tags media_video_tags_video_id_tag_id_0ed54e28_uniq; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_video_tags
    ADD CONSTRAINT media_video_tags_video_id_tag_id_0ed54e28_uniq UNIQUE (video_id, tag_id);


--
-- Name: news_bookmark news_bookmark_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_bookmark
    ADD CONSTRAINT news_bookmark_pkey PRIMARY KEY (id);


--
-- Name: news_bookmark news_bookmark_post_id_user_id_2aceda6e_uniq; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_bookmark
    ADD CONSTRAINT news_bookmark_post_id_user_id_2aceda6e_uniq UNIQUE (post_id, user_id);


--
-- Name: news_category news_category_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_category
    ADD CONSTRAINT news_category_pkey PRIMARY KEY (id);


--
-- Name: news_category news_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_category
    ADD CONSTRAINT news_category_slug_key UNIQUE (slug);


--
-- Name: news_category news_category_title_key; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_category
    ADD CONSTRAINT news_category_title_key UNIQUE (title);


--
-- Name: news_comment news_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_comment
    ADD CONSTRAINT news_comment_pkey PRIMARY KEY (id);


--
-- Name: news_post news_post_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_post
    ADD CONSTRAINT news_post_pkey PRIMARY KEY (id);


--
-- Name: news_post news_post_slug_key; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_post
    ADD CONSTRAINT news_post_slug_key UNIQUE (slug);


--
-- Name: news_post_tags news_post_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_post_tags
    ADD CONSTRAINT news_post_tags_pkey PRIMARY KEY (id);


--
-- Name: news_post_tags news_post_tags_post_id_tag_id_a1986387_uniq; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_post_tags
    ADD CONSTRAINT news_post_tags_post_id_tag_id_a1986387_uniq UNIQUE (post_id, tag_id);


--
-- Name: news_tag news_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_tag
    ADD CONSTRAINT news_tag_pkey PRIMARY KEY (id);


--
-- Name: news_tag news_tag_slug_key; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_tag
    ADD CONSTRAINT news_tag_slug_key UNIQUE (slug);


--
-- Name: news_tag news_tag_title_key; Type: CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_tag
    ADD CONSTRAINT news_tag_title_key UNIQUE (title);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: media_mediafile_uploaded_by_id_3035b28a; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_mediafile_uploaded_by_id_3035b28a ON public.media_mediafile USING btree (uploaded_by_id);


--
-- Name: media_podcast_audio_file_id_9b783bc2; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_podcast_audio_file_id_9b783bc2 ON public.media_podcast USING btree (audio_file_id);


--
-- Name: media_podcast_author_id_4138eee6; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_podcast_author_id_4138eee6 ON public.media_podcast USING btree (author_id);


--
-- Name: media_podcast_category_id_cccf25f2; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_podcast_category_id_cccf25f2 ON public.media_podcast USING btree (category_id);


--
-- Name: media_podcast_cover_image_id_5daffba6; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_podcast_cover_image_id_5daffba6 ON public.media_podcast USING btree (cover_image_id);


--
-- Name: media_podcast_slug_33d2bf60_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_podcast_slug_33d2bf60_like ON public.media_podcast USING btree (slug varchar_pattern_ops);


--
-- Name: media_podcast_tags_podcast_id_649aab6f; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_podcast_tags_podcast_id_649aab6f ON public.media_podcast_tags USING btree (podcast_id);


--
-- Name: media_podcast_tags_tag_id_62630fb2; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_podcast_tags_tag_id_62630fb2 ON public.media_podcast_tags USING btree (tag_id);


--
-- Name: media_video_author_id_2a3f2890; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_video_author_id_2a3f2890 ON public.media_video USING btree (author_id);


--
-- Name: media_video_category_id_59f70c24; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_video_category_id_59f70c24 ON public.media_video USING btree (category_id);


--
-- Name: media_video_slug_5e693ad4_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_video_slug_5e693ad4_like ON public.media_video USING btree (slug varchar_pattern_ops);


--
-- Name: media_video_tags_tag_id_99421d11; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_video_tags_tag_id_99421d11 ON public.media_video_tags USING btree (tag_id);


--
-- Name: media_video_tags_video_id_5adb3330; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_video_tags_video_id_5adb3330 ON public.media_video_tags USING btree (video_id);


--
-- Name: media_video_thumbnail_id_e6a9761f; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_video_thumbnail_id_e6a9761f ON public.media_video USING btree (thumbnail_id);


--
-- Name: media_video_video_file_id_4416c97e; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX media_video_video_file_id_4416c97e ON public.media_video USING btree (video_file_id);


--
-- Name: news_bookmark_post_id_e6876621; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_bookmark_post_id_e6876621 ON public.news_bookmark USING btree (post_id);


--
-- Name: news_bookmark_user_id_db1205ad; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_bookmark_user_id_db1205ad ON public.news_bookmark USING btree (user_id);


--
-- Name: news_category_slug_8bf24efd_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_category_slug_8bf24efd_like ON public.news_category USING btree (slug varchar_pattern_ops);


--
-- Name: news_category_title_175a164c_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_category_title_175a164c_like ON public.news_category USING btree (title varchar_pattern_ops);


--
-- Name: news_comment_post_id_035247f7; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_comment_post_id_035247f7 ON public.news_comment USING btree (post_id);


--
-- Name: news_comment_user_id_ed6ce0db; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_comment_user_id_ed6ce0db ON public.news_comment USING btree (user_id);


--
-- Name: news_post_author_id_d49395b0; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_author_id_d49395b0 ON public.news_post USING btree (author_id);


--
-- Name: news_post_category_id_efb3abe5; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_category_id_efb3abe5 ON public.news_post USING btree (category_id);


--
-- Name: news_post_homepage_section_e006011b; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_homepage_section_e006011b ON public.news_post USING btree (homepage_section);


--
-- Name: news_post_homepage_section_e006011b_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_homepage_section_e006011b_like ON public.news_post USING btree (homepage_section varchar_pattern_ops);


--
-- Name: news_post_is_featured_57e7b33d; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_is_featured_57e7b33d ON public.news_post USING btree (is_featured);


--
-- Name: news_post_is_hero_5b339e74; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_is_hero_5b339e74 ON public.news_post USING btree (is_hero);


--
-- Name: news_post_post_type_15bb5dd4; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_post_type_15bb5dd4 ON public.news_post USING btree (post_type);


--
-- Name: news_post_post_type_15bb5dd4_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_post_type_15bb5dd4_like ON public.news_post USING btree (post_type varchar_pattern_ops);


--
-- Name: news_post_show_on_103250_idx; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_show_on_103250_idx ON public.news_post USING btree (show_on_homepage, homepage_section, homepage_order);


--
-- Name: news_post_show_on_homepage_b20d080d; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_show_on_homepage_b20d080d ON public.news_post USING btree (show_on_homepage);


--
-- Name: news_post_slug_543168_idx; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_slug_543168_idx ON public.news_post USING btree (slug);


--
-- Name: news_post_slug_a1a7d7b8_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_slug_a1a7d7b8_like ON public.news_post USING btree (slug varchar_pattern_ops);


--
-- Name: news_post_status_29dd9a_idx; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_status_29dd9a_idx ON public.news_post USING btree (status, published_at);


--
-- Name: news_post_status_8f2018_idx; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_status_8f2018_idx ON public.news_post USING btree (status, is_featured);


--
-- Name: news_post_status_9a4a7d_idx; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_status_9a4a7d_idx ON public.news_post USING btree (status, is_hero);


--
-- Name: news_post_status_c4571f_idx; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_status_c4571f_idx ON public.news_post USING btree (status, post_type);


--
-- Name: news_post_tags_post_id_4edd83c1; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_tags_post_id_4edd83c1 ON public.news_post_tags USING btree (post_id);


--
-- Name: news_post_tags_tag_id_f6adfa19; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_post_tags_tag_id_f6adfa19 ON public.news_post_tags USING btree (tag_id);


--
-- Name: news_tag_slug_7e2d3f68_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_tag_slug_7e2d3f68_like ON public.news_tag USING btree (slug varchar_pattern_ops);


--
-- Name: news_tag_title_297af55f_like; Type: INDEX; Schema: public; Owner: bloguser
--

CREATE INDEX news_tag_title_297af55f_like ON public.news_tag USING btree (title varchar_pattern_ops);


--
-- Name: accounts_profile accounts_profile_user_id_49a85d32_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_49a85d32_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_mediafile media_mediafile_uploaded_by_id_3035b28a_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_mediafile
    ADD CONSTRAINT media_mediafile_uploaded_by_id_3035b28a_fk_accounts_user_id FOREIGN KEY (uploaded_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_podcast media_podcast_audio_file_id_9b783bc2_fk_media_mediafile_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_podcast
    ADD CONSTRAINT media_podcast_audio_file_id_9b783bc2_fk_media_mediafile_id FOREIGN KEY (audio_file_id) REFERENCES public.media_mediafile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_podcast media_podcast_author_id_4138eee6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_podcast
    ADD CONSTRAINT media_podcast_author_id_4138eee6_fk_accounts_user_id FOREIGN KEY (author_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_podcast media_podcast_category_id_cccf25f2_fk_news_category_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_podcast
    ADD CONSTRAINT media_podcast_category_id_cccf25f2_fk_news_category_id FOREIGN KEY (category_id) REFERENCES public.news_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_podcast media_podcast_cover_image_id_5daffba6_fk_media_mediafile_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_podcast
    ADD CONSTRAINT media_podcast_cover_image_id_5daffba6_fk_media_mediafile_id FOREIGN KEY (cover_image_id) REFERENCES public.media_mediafile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_podcast_tags media_podcast_tags_podcast_id_649aab6f_fk_media_podcast_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_podcast_tags
    ADD CONSTRAINT media_podcast_tags_podcast_id_649aab6f_fk_media_podcast_id FOREIGN KEY (podcast_id) REFERENCES public.media_podcast(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_podcast_tags media_podcast_tags_tag_id_62630fb2_fk_news_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_podcast_tags
    ADD CONSTRAINT media_podcast_tags_tag_id_62630fb2_fk_news_tag_id FOREIGN KEY (tag_id) REFERENCES public.news_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_video media_video_author_id_2a3f2890_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_video
    ADD CONSTRAINT media_video_author_id_2a3f2890_fk_accounts_user_id FOREIGN KEY (author_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_video media_video_category_id_59f70c24_fk_news_category_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_video
    ADD CONSTRAINT media_video_category_id_59f70c24_fk_news_category_id FOREIGN KEY (category_id) REFERENCES public.news_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_video_tags media_video_tags_tag_id_99421d11_fk_news_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_video_tags
    ADD CONSTRAINT media_video_tags_tag_id_99421d11_fk_news_tag_id FOREIGN KEY (tag_id) REFERENCES public.news_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_video_tags media_video_tags_video_id_5adb3330_fk_media_video_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_video_tags
    ADD CONSTRAINT media_video_tags_video_id_5adb3330_fk_media_video_id FOREIGN KEY (video_id) REFERENCES public.media_video(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_video media_video_thumbnail_id_e6a9761f_fk_media_mediafile_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_video
    ADD CONSTRAINT media_video_thumbnail_id_e6a9761f_fk_media_mediafile_id FOREIGN KEY (thumbnail_id) REFERENCES public.media_mediafile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_video media_video_video_file_id_4416c97e_fk_media_mediafile_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.media_video
    ADD CONSTRAINT media_video_video_file_id_4416c97e_fk_media_mediafile_id FOREIGN KEY (video_file_id) REFERENCES public.media_mediafile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_bookmark news_bookmark_post_id_e6876621_fk_news_post_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_bookmark
    ADD CONSTRAINT news_bookmark_post_id_e6876621_fk_news_post_id FOREIGN KEY (post_id) REFERENCES public.news_post(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_bookmark news_bookmark_user_id_db1205ad_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_bookmark
    ADD CONSTRAINT news_bookmark_user_id_db1205ad_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_comment news_comment_post_id_035247f7_fk_news_post_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_comment
    ADD CONSTRAINT news_comment_post_id_035247f7_fk_news_post_id FOREIGN KEY (post_id) REFERENCES public.news_post(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_comment news_comment_user_id_ed6ce0db_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_comment
    ADD CONSTRAINT news_comment_user_id_ed6ce0db_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_post news_post_author_id_d49395b0_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_post
    ADD CONSTRAINT news_post_author_id_d49395b0_fk_accounts_user_id FOREIGN KEY (author_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_post news_post_category_id_efb3abe5_fk_news_category_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_post
    ADD CONSTRAINT news_post_category_id_efb3abe5_fk_news_category_id FOREIGN KEY (category_id) REFERENCES public.news_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_post_tags news_post_tags_post_id_4edd83c1_fk_news_post_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_post_tags
    ADD CONSTRAINT news_post_tags_post_id_4edd83c1_fk_news_post_id FOREIGN KEY (post_id) REFERENCES public.news_post(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_post_tags news_post_tags_tag_id_f6adfa19_fk_news_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: bloguser
--

ALTER TABLE ONLY public.news_post_tags
    ADD CONSTRAINT news_post_tags_tag_id_f6adfa19_fk_news_tag_id FOREIGN KEY (tag_id) REFERENCES public.news_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict tpkw4uHrx2pQljpUmdISURIPFfTibcra3F8ZPN7K6D42OghxmpgqaBwdMuP7kNx

