version: "3.9"

services:
  db:
    image: postgres:16
    container_name: blog_db
    restart: always
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: blog_web
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      SECRET_KEY: "django-insecure-super-secret-key"
      DB_NAME: blogdb
      DB_USER: bloguser
      DB_PASSWORD: blogpass
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:
