# Generated by Django 5.2.14 on 2026-06-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(default='تومان', max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('active', models.BooleanField(default=False)),
                ('type', models.CharField(default='currency', max_length=50)),
                ('raw_symbol', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(default='fastforex', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
