# Generated by Django 5.2.14 on 2026-06-01 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_at', '-created_at')},
        ),
        migrations.AddField(
            model_name='post',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='homepage_section',
            field=models.CharField(choices=[('none', 'None'), ('hero', 'Hero'), ('top_stories', 'Top Stories'), ('latest', 'Latest'), ('opinion', 'Opinion'), ('explainers', 'Explainers'), ('how_to', 'How To'), ('market', 'Market'), ('business', 'Business'), ('culture', 'Culture'), ('work_life', 'Work & Life'), ('green', 'Green')], db_index=True, default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hero',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('featured_talk', 'گفتگوهای شاخص'), ('interview', 'مصاحبه'), ('note', 'یادداشت'), ('video_call', 'ارتباط تصویری'), ('news', 'خبر'), ('analysis', 'تحلیل'), ('report', 'گزارش'), ('chart', 'نمودار')], db_index=True, default='news', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='show_on_homepage',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'post_type'], name='news_post_status_c4571f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'is_featured'], name='news_post_status_8f2018_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'is_hero'], name='news_post_status_9a4a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['show_on_homepage', 'homepage_section', 'homepage_order'], name='news_post_show_on_103250_idx'),
        ),
    ]
