# Generated by Django 5.2.14 on 2026-06-11 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_options_post_homepage_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('main', 'Main'), ('top_left', 'Top Left'), ('bottom_left', 'Bottom Left'), ('bottom_center', 'Bottom Center'), ('bottom_right', 'Bottom Right')], max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('slot',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/audios/'),
        ),
        migrations.AddField(
            model_name='post',
            name='embed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='media_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('none', 'بدون رسانه'), ('video', 'ویدیو'), ('podcast', 'پادکست')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'media_type'], name='news_post_status_2c0758_idx'),
        ),
        migrations.AddField(
            model_name='homeheroselection',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_hero_selections', to='news.post'),
        ),
    ]
