# Generated by Django 5.2.14 on 2026-06-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_homeheroselection_post_audio_file_post_embed_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideoSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('main', 'Main Video'), ('top', 'Top Small Video'), ('middle', 'Middle Small Video'), ('bottom', 'Bottom Small Video')], max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_video_selections', to='news.post')),
            ],
            options={
                'ordering': ('slot',),
            },
        ),
    ]
