# Generated by Django 5.2.14 on 2026-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تبلیغ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='تصویر')),
                ('label', models.CharField(default='تبلیغ', max_length=50, verbose_name='برچسب')),
                ('button_text', models.CharField(default='مشاهده بیشتر', max_length=50, verbose_name='متن دکمه')),
                ('href', models.URLField(verbose_name='لینک مقصد')),
                ('slot', models.CharField(choices=[('home_medium_news', 'زیر اخبار میانی (وسط صفحه)'), ('home_sidebar', 'سایدبار (ستون کناری)'), ('home_bottom', 'پایین صفحه')], max_length=50, unique=True, verbose_name='جایگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
                'ordering': ['-id'],
            },
        ),
    ]
