# Generated by Django 5.2.14 on 2026-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('crypto', 'Crypto'), ('forex', 'Forex'), ('commodity', 'Commodity'), ('index', 'Index')], max_length=30)),
                ('value', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('display_value', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='alpha_vantage', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('from_currency', models.CharField(blank=True, max_length=20)),
                ('to_currency', models.CharField(blank=True, default='USD', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('crypto', 'Crypto'), ('forex', 'Forex'), ('commodity', 'Commodity'), ('index', 'Index')], max_length=30)),
                ('provider', models.CharField(default='alpha_vantage', max_length=50)),
                ('provider_function', models.CharField(default='CURRENCY_EXCHANGE_RATE', max_length=100)),
                ('target_currency', models.CharField(choices=[('USD', 'US Dollar'), ('IRR', 'Iranian Rial')], default='USD', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('active', models.BooleanField(default=True)),
                ('enabled_for_sync', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Symbol',
                'verbose_name_plural': 'Market Symbols',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
